# Generated by Django 5.0 on 2023-12-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_phoneno', models.CharField(max_length=70)),
                ('emp_mailid', models.CharField(max_length=70)),
                ('emp_add', models.CharField(max_length=80)),
                ('emp_sal', models.CharField(max_length=70)),
            ],
        ),
    ]
