# Generated by Django 5.0 on 2023-12-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp_mailid',
            new_name='Emp_Gender',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='emp_phoneno',
            new_name='Emp_email',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='emp_add',
            new_name='Emp_message',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='emp_name',
            new_name='Emp_name',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='emp_sal',
        ),
    ]
